/**
 * themegen — テーマ生成器。
 *
 * 決定性 MUST（R5 AM-1'）: 同一入力 → bit 同一出力・2回連続実行 diff 0・
 * override の与え順に依存しない（正準順ソート）。
 * 順序固定: extract → map → generate（写像を先に適用・未知キーは error reject・silent drop 禁止）。
 */

import {
  COLOR_KEYS,
  CONTRACT_VERSION,
  EXCLUDED_NAMESPACES,
  SHADOW_KEYS,
  isContractTokenName,
  isExtensionTokenName,
} from './contract.js';
import { parseTokenValue } from './grammar.js';
import { parseThemeFile, isRootScopeSelector, type Block } from './parser.js';
import { transitiveDependents } from './resolve.js';
import { classifyTokenName, type MappingTableId } from './codemod-map.js';

export class ThemegenError extends Error {}

/**
 * @theme に出してよいキーか（契約・拡張トークン、または除外 namespace の pass-through 宣言）。
 * 除外 namespace（--breakpoint-* ・ --container-*）は Tailwind の正規 @theme トークンとして宣言は
 * 正当 — codemod は変換対象外としてそのまま維持する（#24 point4: fatal ではない）。
 */
function isAllowedThemeKey(name: string): boolean {
  return (
    isContractTokenName(name) ||
    isExtensionTokenName(name) ||
    EXCLUDED_NAMESPACES.some((ns) => name.startsWith(ns))
  );
}

/** パッケージ版 — プラグマ `@themegen <ver>` に焼く（dx D4）。 */
export const THEMEGEN_VERSION = '1.0.0';

/* ------------------------------------------------------------------ */
/* 正準順                                                                */
/* ------------------------------------------------------------------ */

const CANONICAL_ORDER = new Map<string, number>();
COLOR_KEYS.forEach((k, i) => CANONICAL_ORDER.set(`--color-${k}`, i));
SHADOW_KEYS.forEach((k, i) => CANONICAL_ORDER.set(`--shadow-${k}`, 100 + i));

/** 契約キー正準順 → 拡張・その他はアルファベット順（決定性のための全順序） */
export function canonicalCompare(a: string, b: string): number {
  const ia = CANONICAL_ORDER.get(a);
  const ib = CANONICAL_ORDER.get(b);
  if (ia !== undefined && ib !== undefined) return ia - ib;
  if (ia !== undefined) return -1;
  if (ib !== undefined) return 1;
  return a < b ? -1 : a > b ? 1 : 0;
}

export function sortDecls(decls: ReadonlyMap<string, string>): [string, string][] {
  return [...decls.entries()].sort(([a], [b]) => canonicalCompare(a, b));
}

/* ------------------------------------------------------------------ */
/* fill（AM-1 — 局所スコープの充足はツール維持）                          */
/* ------------------------------------------------------------------ */

/**
 * 局所スコープの fill を決定的に計算する純関数。
 * fill = 「スコープが上書きしたトークンに（推移的に）依存する base の派生式のうち、
 * authored に書かれていないもの」。値は base（root/parent）の式をそのまま写す
 * （F-1: authored 宣言＋契約版の派生式表から決定的に再計算可能）。
 */
export function computeFillForScope(
  base: ReadonlyMap<string, string>,
  authored: ReadonlyMap<string, string>,
): Map<string, string> {
  const graph = new Map<string, Set<string>>();
  for (const [name, value] of base) {
    try {
      graph.set(name, parseTokenValue(name, value).refs);
    } catch {
      // base の文法エラーは base 側 validate の管轄 — fill は当該トークンを式なし扱い
      graph.set(name, new Set());
    }
  }
  const needed = new Set<string>();
  for (const overridden of authored.keys()) {
    for (const dep of transitiveDependents(graph, overridden)) needed.add(dep);
  }
  const fill = new Map<string, string>();
  for (const name of [...needed].sort(canonicalCompare)) {
    if (authored.has(name)) continue;
    const value = base.get(name);
    if (value !== undefined) fill.set(name, value);
  }
  return fill;
}

/* ------------------------------------------------------------------ */
/* 生成                                                                  */
/* ------------------------------------------------------------------ */

export interface ThemeDocument {
  /** 契約版（プラグマに焼く） */
  contract: string;
  /** 対になる .components.css の import（任意 — TH-02） */
  componentsImport?: string;
  /** ルートブロック（@theme / --plain 時 :root）の宣言 */
  theme: Record<string, string>;
  /** スコープブロック（selector → authored 宣言）。fill は generate が再計算する。 */
  scopes?: Record<string, Record<string, string>>;
}

export interface GenerateOptions {
  /** :root ラッパで出す（serve/suite stage1 — R2⑩ themegen --plain） */
  plain?: boolean;
  /** --container 判定用（fill 対象の root スコープ判定に使う） */
  containerSelector?: string;
}

const FILL_START = (ver: string) =>
  `  /* @nene2-fill:start — generated by themegen ${ver}; DO NOT EDIT (repair: npx nene2-tokens fill) */`;
const FILL_END = `  /* @nene2-fill:end */`;

function renderBlock(
  header: string,
  entries: [string, string][],
  fill: [string, string][],
): string {
  const lines: string[] = [`${header} {`];
  for (const [name, value] of entries) lines.push(`  ${name}: ${value};`);
  if (fill.length > 0) {
    lines.push(FILL_START(THEMEGEN_VERSION));
    for (const [name, value] of fill) lines.push(`  ${name}: ${value};`);
    lines.push(FILL_END);
  }
  lines.push('}');
  return lines.join('\n');
}

/**
 * ThemeDocument → テーマ CSS（決定的: キーは正準順・スコープはセレクタ辞書順・
 * fill は computeFillForScope の出力）。
 */
export function generateTheme(doc: ThemeDocument, opts: GenerateOptions = {}): string {
  const rootEntries = sortDecls(new Map(Object.entries(doc.theme)));
  for (const [name] of rootEntries) {
    if (!isAllowedThemeKey(name)) {
      throw new ThemegenError(
        `unknown key '${name}' — not contract v${CONTRACT_VERSION}, not an extension token, and not an excluded namespace; refusing to generate (silent drop is prohibited). Map it first: nene2-tokens extract --map <table>`,
      );
    }
  }
  const parts: string[] = [`/* @nene2-contract ${doc.contract} @themegen ${THEMEGEN_VERSION} */`];
  if (doc.componentsImport !== undefined) {
    parts.push(`@import '${doc.componentsImport}' layer(components);`);
  }
  parts.push(renderBlock(opts.plain ? ':root' : '@theme', rootEntries, []));

  const base = new Map(Object.entries(doc.theme));
  const scopeSelectors = Object.keys(doc.scopes ?? {}).sort();
  for (const selector of scopeSelectors) {
    const authoredRecord = doc.scopes![selector]!;
    for (const name of Object.keys(authoredRecord)) {
      if (!isAllowedThemeKey(name)) {
        throw new ThemegenError(
          `unknown key '${name}' in scope '${selector}' — refusing to generate (silent drop is prohibited)`,
        );
      }
    }
    const authored = new Map(Object.entries(authoredRecord));
    const isRoot = isRootScopeSelector(selector, opts.containerSelector);
    const fill = isRoot ? new Map<string, string>() : computeFillForScope(base, authored);
    parts.push('');
    parts.push(renderBlock(selector, sortDecls(authored), sortDecls(fill)));
  }
  return parts.join('\n') + '\n';
}

/* ------------------------------------------------------------------ */
/* extract（extract → map → generate の第1工程）                          */
/* ------------------------------------------------------------------ */

export interface ExtractOptions {
  /** 適用する写像表（省略時 common）。写像は名前検査より先に適用 MUST（i18n §2-3） */
  map?: MappingTableId;
}

/** テーマ CSS → ThemeDocument（写像表を適用してから出力・未知キーは error reject） */
export function extractTheme(source: string, opts: ExtractOptions = {}): ThemeDocument {
  const parsed = parseThemeFile(source);
  if (parsed.errors.length > 0) {
    throw new ThemegenError(
      `theme file has structural errors — fix before extract: ${parsed.errors[0]!.message} (line ${parsed.errors[0]!.line})`,
    );
  }
  const table: MappingTableId = opts.map ?? 'common';

  const mapBlock = (block: Block): Record<string, string> => {
    const out: Record<string, string> = {};
    for (const d of block.decls) {
      const cls = classifyTokenName(d.name, table);
      if (cls.kind === 'reject') {
        throw new ThemegenError(
          `unknown key '${d.name}' (line ${d.line}) — not contract v${CONTRACT_VERSION}, not an extension token, and not in codemod mapping table '${table}'; refusing to extract (silent drop is prohibited)`,
        );
      }
      // rename/contract はターゲット名、passthrough（除外 namespace）は宣言をそのまま維持する
      // （#24 point4: fatal null にしない — breakpoint を宣言するテーマでも codemod を走らせる）。
      const mapped = cls.name;
      const value = mapValueRefs(d.value, table);
      // 語彙統一による直エイリアスの畳み込み: 写像後に `X: var(X)` の恒等形になった宣言は
      // 同義二重名（ok/success 等）の alias が消滅した痕跡 — 決定的に除去する
      // （R2⑥(A) 同義二重名禁止の帰結。records 現物: --color-success: var(--color-ok)）。
      if (value === `var(${mapped})`) continue;
      if (mapped in out && out[mapped] !== value) {
        throw new ThemegenError(
          `mapping collision: '${d.name}' (line ${d.line}) maps to '${mapped}' which already holds a different value — resolve the duplicate in the source theme first (silent overwrite is prohibited)`,
        );
      }
      out[mapped] = value;
    }
    return out;
  };

  const root = parsed.blocks.find((b) => b.kind === 'theme' || b.kind === 'container');
  if (!root) throw new ThemegenError('no @theme/:root block found — nothing to extract');
  const doc: ThemeDocument = {
    contract: CONTRACT_VERSION,
    theme: mapBlock(root),
  };
  const scopes: Record<string, Record<string, string>> = {};
  for (const block of parsed.blocks) {
    if (block === root || block.kind !== 'scope') continue;
    // fill 領域は再計算対象なので extract しない（authored のみが入力）
    const authoredOnly: Block = {
      ...block,
      decls: block.decls.filter((d) => d.region === 'authored'),
    };
    scopes[block.selector] = mapBlock(authoredOnly);
  }
  if (Object.keys(scopes).length > 0) doc.scopes = scopes;
  const componentsImport = parsed.imports.find((imp) => /layer\(components\)/.test(imp.text));
  if (componentsImport) {
    const m = /@import\s+'([^']+)'/.exec(componentsImport.text);
    if (m) doc.componentsImport = m[1]!;
  }
  return doc;
}

/** 値の中の var(--旧名) も写像する（写像は名前と参照の両方に適用） */
function mapValueRefs(value: string, table: MappingTableId): string {
  return value.replace(/var\(\s*(--[a-zA-Z0-9-]+)\s*\)/g, (_whole, name: string) => {
    const cls = classifyTokenName(name, table);
    if (cls.kind === 'reject') {
      throw new ThemegenError(
        `unknown key '${name}' referenced in value — refusing (silent drop is prohibited)`,
      );
    }
    // 除外 namespace は宣言は素通しだが var() 参照は契約 error（#24 point4 の切り分け・Case D）。
    if (cls.kind === 'passthrough') {
      throw new ThemegenError(
        `var(${name}) references the excluded --breakpoint-* ・ --container-* namespace — prohibited (emits invalid CSS with no error, Case D)`,
      );
    }
    return `var(${cls.name})`;
  });
}

/* ------------------------------------------------------------------ */
/* plain 変換（@theme ↔ :root — 機械的ラッパ1行変換・R2⑩）               */
/* ------------------------------------------------------------------ */

export function toPlain(source: string): string {
  return source.replace(/(^|\n)@theme\s*\{/, '$1:root {');
}

export function toTheme(source: string): string {
  return source.replace(/(^|\n):root\s*\{/, '$1@theme {');
}

/* ------------------------------------------------------------------ */
/* fill（ファイル書き換え — 決定的）                                       */
/* ------------------------------------------------------------------ */

/**
 * ファイル内の局所スコープブロックの fill 領域を再計算して書き直す。
 * root ブロックが同一ファイルに無い場合は parentSource が必須（records の分離局所テーマ形）。
 */
export function fillSource(source: string, parentSource?: string): string {
  const parsed = parseThemeFile(source);
  const root = parsed.blocks.find((b) => b.kind === 'theme' || b.kind === 'container');
  let base: Map<string, string>;
  if (root) {
    base = new Map(root.decls.map((d) => [d.name, d.value]));
  } else if (parentSource !== undefined) {
    const parent = parseThemeFile(parentSource);
    const parentRoot = parent.blocks.find((b) => b.kind === 'theme' || b.kind === 'container');
    if (!parentRoot) throw new ThemegenError('--parent file has no @theme/:root block');
    base = new Map(parentRoot.decls.map((d) => [d.name, d.value]));
  } else {
    throw new ThemegenError(
      'file has no @theme/:root block — pass the brand theme with --parent <file> (scoped theme files fill against their parent)',
    );
  }

  // ブロックを後ろから書き換え（オフセットを保つ）
  let out = source;
  const scopeBlocks = parsed.blocks.filter(
    (b) => b !== root && b.kind === 'scope' && !isRootScopeSelector(b.selector),
  );
  for (const block of [...scopeBlocks].reverse()) {
    const authored = new Map(
      block.decls.filter((d) => d.region === 'authored').map((d) => [d.name, d.value]),
    );
    const fill = computeFillForScope(base, authored);
    const rendered = renderBlock(block.selector, sortDecls(authored), sortDecls(fill));
    const blockRegex = blockSpan(out, block.selector);
    if (!blockRegex) throw new ThemegenError(`cannot locate block '${block.selector}' for rewrite`);
    out = out.slice(0, blockRegex.start) + rendered + out.slice(blockRegex.end);
  }
  return out;
}

/** selector から始まるブロックの文字範囲を素朴に特定（token-only 文法にはネストが無い） */
function blockSpan(source: string, selector: string): { start: number; end: number } | null {
  const idx = source.indexOf(`${selector} {`);
  const idxTight = idx === -1 ? source.indexOf(`${selector}{`) : idx;
  if (idxTight === -1) return null;
  const open = source.indexOf('{', idxTight);
  const close = source.indexOf('}', open);
  if (open === -1 || close === -1) return null;
  return { start: idxTight, end: close + 1 };
}
